### ISSUE TITLE
2 product price still carry decimal place

### ISSUE THREAD

**Issue by dereklokgithub** [dereklokgithub/PSM-Internal#5]
at least 2 products still carry decimal place. 

![image](https://cloud.githubusercontent.com/assets/13758674/17768665/9b7b6c5e-6567-11e6-8755-de5235162684.png)

action required:
1. find out the 3 items that are missing from the product list that you have exported before
2. roundup the price and update to PSM

**Comment by shirshirmok** [comment]
@dereklokgithub Updated the above 2 product prices in both test and production sites

**Comment by dereklokgithub** [comment]
checked. Done
