### ISSUE TITLE
Product price $.0 issue

### ISSUE THREAD

**Issue by dereklokgithub** [dereklokgithub/PSM-Internal#6]
Show decimal place ONLY when the product price contains decimal place. E.g, don't show $68.0

**Comment by shirshirmok** [comment]
@dereklokgithub Please test.

should leo hide the .0 in price column (shopping cart page, float cart, checkout page) ?
![2016-08-23 8 35 50](https://cloud.githubusercontent.com/assets/19773700/17892040/c0001b34-6971-11e6-89a1-ac4b81790b27.png)

**Comment by dereklokgithub** [comment]
checked. Done
