### ISSUE TITLE
Wrong product photos

### ISSUE THREAD

**Issue by dereklokgithub** [dereklokgithub/PSM-Internal#7]
The 2 tables photos is swapped. The first one should be the smaller one ( cheaper )and the 2nd one should be the larger one. Now it looks like the smaller table is more expensive than the larger one 

![image](https://cloud.githubusercontent.com/assets/13758674/17888525/f342760e-695d-11e6-8ea2-104509fa4056.png)

**Comment by shirshirmok** [comment]
@dereklokgithub Reloaded photos in production site.

**Comment by dereklokgithub** [comment]
checked. thanks
